enum PieceType {
  PAWN = "PAWN",
  ROOK = "ROOK",
  KNIGHT = "KNIGHT",
  BISHOP = "BISHOP",
  QUEEN = "QUEEN",
  KING = "KING",
  EMPTY_SQUARE = "EMPTY_SQUARE",
  SELECTED_SQUARE = "SELECTED_SQUARE",
  POSSIBLE_SQUARE = "POSSIBLE_SQUARE",
}

export default PieceType;
